language: c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  # for unit tests
  - sudo apt-get install -y check
  - sudo apt-get install -y libsubunit-dev
  # for static code analysis
  # - sudo apt-get install -y cppcheck
  # - sudo apt-get install -y rats
  # for test code coverage
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov
  # for HTML validation
  - sudo apt-get install -y tidy

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs cppcheck 2>&1
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs rats --language=c
  - git clone --depth 10 https://github.com/proftpd/proftpd.git
  - mkdir -p proftpd/contrib/mod_explain/
  - cp *.[ch] proftpd/contrib/mod_explain/
  - cp mod_explain.* proftpd/contrib/mod_explain/
  - cp Makefile.in proftpd/contrib/mod_explain/
  - cp config* proftpd/contrib/mod_explain/
  - cp install-sh proftpd/contrib/mod_explain/
  - cp -R t/ proftpd/contrib/mod_explain/t/
  - cd proftpd
  - ./configure LIBS='-lm -lsubunit -lrt -pthread' --enable-devel=coverage --enable-dso --enable-tests --with-shared=mod_explain
  - make
  # Last, a build with a static module, and run the tests
  - make clean
  - ./configure LIBS='-lm -lsubunit -lrt -pthread' --enable-devel=coverage --enable-tests --with-modules=mod_explain
  - make
  - cd contrib/mod_explain && make TEST_VERBOSE=1 check && cd ../../

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  # capture the test coverage info
  - lcov --ignore-errors gcov,source --base-directory ${TRAVIS_BUILD_DIR}/proftpd/contrib/mod_explain --directory proftpd/contrib/mod_explain --capture --output-file coverage.info
  # filter out system and test code
  - lcov --remove coverage.info 'api/*' 't/*' '/usr/*' --output-file coverage.info
  # debug before upload
  - lcov --list coverage.info
  # upload coverage info to coveralls
  - coveralls-lcov coverage.info
  # Run some validation on the docs
  # - tidy -errors -omit -q mod_explain.html
