env: TRAVIS_CI=true
language: c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  # for unit tests
  - sudo apt-get install -y check
  # for static code analysis
  - sudo apt-get install -y cppcheck rats
  # for test code coverage
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs cppcheck 2>&1
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs rats --language=c
  - git clone https://github.com/proftpd/proftpd.git
  - cd proftpd && git checkout explain-errors && cd ..
  - mkdir -p proftpd/contrib/mod_explain/
  - cp *.[ch] proftpd/contrib/mod_explain/
  - cp mod_explain.* proftpd/contrib/mod_explain/
  - cp Makefile.in proftpd/contrib/mod_explain/
  - cp config* proftpd/contrib/mod_explain/
  - cp install-sh proftpd/contrib/mod_explain/
  - cp -R t/ proftpd/contrib/mod_explain/t/
  - cd proftpd
  - ./configure --enable-devel=coverage --enable-dso --enable-tests --with-shared=mod_explain --with-includes=/usr/include/libxml2
  - make
  # Last, a build with a static module, and run the tests
  - make clean
  - ./configure --enable-devel=coverage --enable-tests --with-modules=mod_explain
  - make
  - cd contrib/mod_explain && make TEST_VERBOSE=1 check && cd ../../

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  # capture the test coverage info
  - lcov --ignore-errors gcov,source --base-directory ${TRAVIS_BUILD_DIR}/proftpd/contrib/mod_explain --directory proftpd/contrib/mod_explain --capture --output-file coverage.info
  # filter out system and test code
  - lcov --remove coverage.info 'api/*' 't/*' '/usr/*' --output-file coverage.info
  # debug before upload
  - lcov --list coverage.info
  # upload coverage info to coveralls
  - coveralls-lcov --repo-token FMyT3YddteWuTLNzK6RFsAAJA7HQCHAfn coverage.info
